// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABllUxryzV3JEw8GVk4VZ_DNlGPSjs8Uk',
    appId: '1:564593243541:web:9fac7155775f462664329c',
    messagingSenderId: '564593243541',
    projectId: 'appp-73d34',
    authDomain: 'appp-73d34.firebaseapp.com',
    storageBucket: 'appp-73d34.firebasestorage.app',
    measurementId: 'G-J72BDLXYYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5wfCCIwazQJuTmDFoOGzJxmhJJqApxvc',
    appId: '1:564593243541:android:1942f5f48d1ec79564329c',
    messagingSenderId: '564593243541',
    projectId: 'appp-73d34',
    storageBucket: 'appp-73d34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtAw10hd_UqqrxPeznPSIcgiFmmgTxkNU',
    appId: '1:564593243541:ios:990a4b5ce6247e5264329c',
    messagingSenderId: '564593243541',
    projectId: 'appp-73d34',
    storageBucket: 'appp-73d34.firebasestorage.app',
    iosClientId: '564593243541-u39k75trfsl7himc5jg4megfsfm7pbgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtAw10hd_UqqrxPeznPSIcgiFmmgTxkNU',
    appId: '1:564593243541:ios:990a4b5ce6247e5264329c',
    messagingSenderId: '564593243541',
    projectId: 'appp-73d34',
    storageBucket: 'appp-73d34.firebasestorage.app',
    iosClientId: '564593243541-u39k75trfsl7himc5jg4megfsfm7pbgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABllUxryzV3JEw8GVk4VZ_DNlGPSjs8Uk',
    appId: '1:564593243541:web:f68a2b8eb9720e8064329c',
    messagingSenderId: '564593243541',
    projectId: 'appp-73d34',
    authDomain: 'appp-73d34.firebaseapp.com',
    storageBucket: 'appp-73d34.firebasestorage.app',
    measurementId: 'G-R2CPLESMHM',
  );
}
